### ISSUE TITLE
Failure to run tests

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#259]
From https://jabbr.net/#/rooms/xbehavenet

```
C:\Source>packages\xunit.runner.console.2.1.0-beta2-build2981\tools\xunit.console.exe DataProviders.Tests\bin\Debug\Da
taProviders.Tests.dll -diagnostics
xUnit.net console test runner (64-bit .NET 4.0.30319.34209)
Copyright (C) 2015 Outercurve Foundation.

Discovering: DataProviders.Tests (method display = ClassAndMethod, parallel test collections = True, max threads = 8)
   DataProviders.Tests: Exception during discovery:
System.IO.FileLoadException: Could not load file or assembly 'xunit.execution.desktop, Version=2.0.0.2929, Culture=neutral, PublicKeyToken=8d05b1bb7a6
fdb6c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x801310
40)
File name: 'xunit.execution.desktop, Version=2.0.0.2929, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'
   at Xbehave.Execution.ScenarioDiscoverer.<Discover>d__0.MoveNext()
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForMethod(ITestMethod testMethod, Boolean includeSourceInformation, IMessageBus messageBus, ITes
tFrameworkDiscoveryOptions discoveryOptions)
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForType(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFra
meworkDiscoveryOptions discoveryOptions)
   at Xunit.Sdk.TestFrameworkDiscoverer.FindTestsForTypeAndWrapExceptions(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageB
us, ITestFrameworkDiscoveryOptions discoveryOptions)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   DataProviders.Tests: Exception during discovery:
System.IO.FileLoadException: Could not load file or assembly 'xunit.execution.desktop, Version=2.0.0.2929, Culture=neutral, PublicKeyToken=8d05b1bb7a6
fdb6c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x801310
40)
File name: 'xunit.execution.desktop, Version=2.0.0.2929, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'
   at Xbehave.Execution.ScenarioDiscoverer.<Discover>d__0.MoveNext()
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForMethod(ITestMethod testMethod, Boolean includeSourceInformation, IMessageBus messageBus, ITes
tFrameworkDiscoveryOptions discoveryOptions)
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForType(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFra
meworkDiscoveryOptions discoveryOptions)
   at Xunit.Sdk.TestFrameworkDiscoverer.FindTestsForTypeAndWrapExceptions(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageB
us, ITestFrameworkDiscoveryOptions discoveryOptions)
```

**Comment by adamralph** [comment]
No further input from reporter of issue. Closing.
